### ISSUE TITLE
Preprocessing Falcon request object stopped working

### ISSUE THREAD

**Issue by codingadvocate** [hugapi/hug#833]
**Overview:**
For a couple years I've used a Falcon middleware to dump the payload, authenticate user/key, and validate some payload components - all prior to allowing access to Hug wrapped functions.  In short the work around was simply reading and then resetting/overriding the request.stream:

`rawData = request.stream.read()`
`request.stream = io.BytesIO(rawData)`

[Note, attempting to overwrite the request.stream object was detailed in a similar work around in request #Falcon Request Object #501  , but these methods no longer work.]

This project last stabilized on Hug version 2.3.0, but as any active project... it eventually needs to move to the latest-and-greatest platform dependencies.  Upgrading to the latest Hug version (2.6.0 at the time of this post) hit a problem, but it turns out the problem started with Hug 2.5.1.

**The problem:**
The payload reset trick no longer works, and it appears empty to Hug - as reported from hug\interface.py, exception in gather_parameters. (see below for stacktrace).  

Is this known/expected? Is there a newer work around with more recent versions of Hug or Falcon? 

**Failing environments:**
It doesn't matter in this case, but for completeness... I've tested and received similar results across Linux/Windows environments, and Python 3.6/3.7 builds:
- Windows 10 Pro, using Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)]
- Windows 10 Pro, using Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)]
- Windows 2016 Server, using Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)]
- CentOS Linux release 7.5.1804 (Core), using Python 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

This project uses a Twisted WSGI server in a multi-process framework, which isn't conducive for minimal test cases.  So for convenience I am attaching a unit test that works with 'hug -f' on the command line.  The api service is apiPayloadTest.py and the client is getRequest.py.
 
**To reproduce:**
First run the following to start the hug wsgi server; note, this is the window you will see the stacktrace:
> hug -f apiPayloadTest.py

Then run this command in a new shell/window, which calls requests.get:
> python .\getRequest.py

**Sample stacktrace:**
With Hug <=2.5.0 you should see it pass.  But 2.5.1+ (tested up to 2.6.0) is failing.  Here is a sample stacktrace using the above test:

> Serving on :8000...
User: myName
Traceback (most recent call last):
  File "e:\software\python37\lib\wsgiref\handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "e:\software\python37\lib\site-packages\falcon\api.py", line 269, in __call__
    responder(req, resp, **params)
  File "e:\software\python37\lib\site-packages\hug\interface.py", line 946, in __call__
    raise exception
  File "e:\software\python37\lib\site-packages\hug\interface.py", line 909, in __call__
    request, response, context, api_version, **kwargs
  File "e:\software\python37\lib\site-packages\hug\interface.py", line 732, in gather_parameters
    body = body_formatter(body, content_length=request.content_length, **content_params)
  File "e:\software\python37\lib\site-packages\hug\input_format.py", line 43, in json
    return json_converter.loads(text(body, charset=charset))
  File "e:\software\python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "e:\software\python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "e:\software\python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
127.0.0.1 - - [03/Jan/2020 14:58:46] "GET /test HTTP/1.1" 500 59
----------------------------------------

[testCase.zip](https://github.com/hugapi/hug/files/4020995/testCase.zip)

**Comment by codingadvocate** [comment]
**Code that causes the break:**
Looks like between Hug 2.5.0 and 2.5.1, the interface.gather_parameters function changes how it assigns the body...

Hug 2.5.0:
body = request.stream

Hug 2.5.1:
body = request.bounded_stream

Since hug migrated to using the newer wrapped version (bounded_stream), the previous reset on request.stream won't work since bounded_stream would be empty from the stream read.  Any reset on the stream would not propagate to bounded_stream, since that's set through a few different falcon function calls. 


**Workaround:**
I don't like overriding internal variables, but I have a work around.

Previous:
`rawData = request.stream.read(request.content_length or 0)`
`request.stream = io.BytesIO(rawData)`

New:
`from falcon.request_helpers import BoundedStream as FalconBoundedStream`
`rawData = request.stream.read(request.content_length or 0)`
`request._bounded_stream = FalconBoundedStream(io.BytesIO(rawData), request.content_length)`

I hope this helps someone hitting this in the future.

**Comment by codingadvocate** [comment]
Migrating to using the falcon wrapped stream seems like a good idea.  But falcon doesn't allow the same workaround for a direct variable override, meaning you can't assign a new value to bounded_stream, since "_bounded_stream" is what's set and used within falcon.  

If falcon had a more public way of (re)setting the bounded_stream, this wouldn't be a problem.  Or if hug used the safer stream read [e.g. request.stream.read(request.content_length or 0)], but stayed on the stream object, this also wouldn't be a problem for code that needs falcon to read the payload, but provide it again to hug.

I'm at a loss on whether this should be considered a bug for hug; I'm going to close the ticket.
